### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by m4b** [AlexAltea/capstone.js#2]
Don't know if this project is still live, if not a shame, because seems pretty awesome.

But your suggested install mechanism: `bower install capstone` seems to fail with `bower ENOTFOUND     Package capstone not found`

**Comment by AlexAltea** [comment]
@m4b: Back then, I followed _some_ instructions I found _somewhere_ trying to get this repository indexed in Bower. Apparently that didn't work, however since this repo didn't receive much attention I just ignored the problem.

However, I will fix this problem this weekend and take the opportunity to update to the latest Capstone version and pushing new precompiled files. :-)

**Comment by m4b** [comment]
@AlexAltea: _awesome_; if you need any help, let me know.  

I followed [these bower instructions](http://bower.io/docs/creating-packages/#register) for [silicon-hex-table](http://github.com/m4b/silicon-hex-table) and it worked well.

So I'm in the middle of wrapping this into a web-component and I'm really excited by the possibilities.  Once I get something half decent working, I'll send you the repo.

I am running into a minor problem with the load time of the library, it can take upwards of 6 seconds, so I'm experimenting with web workers, since that's unacceptable.  But in the event this doesn't help, I might need a stripped down version for just x86-64, and ideally arm64; unfortunately, I was unable to build the emscripten SDK (never even heard of this), so I couldn't build the 600k individual target version you spoke of.

**Comment by AlexAltea** [comment]
Fixed, it is registered under the name `capstonejs` now.
Thanks for the links, by the way.
