### ISSUE TITLE
detail.op isn't given on X86

### ISSUE THREAD

**Issue by darkf** [AlexAltea/capstone.js#8]
Take the homepage's example code and add `d.option(cs.OPT_DETAIL, cs.OPT_ON);`

Now try to print `instr.detail.op`, it should be an array, but it's not given. `op_count` from [here](https://github.com/AlexAltea/capstone.js/blob/master/src/capstone-wrapper.js#L320) is also 0, but shouldn't it be a real value if detail mode is on?

**Comment by AlexAltea** [comment]
Hey @darkf! Not sure what's causing this, it's very likely that I failed writing the parser for those structures. I'm a bit busy these days, but I'll try to fix this issue (and update to Capstone 4.0.1!) in early May.

**Comment by AlexAltea** [comment]
I've just updated to Capstone 4.0.1 and fixed a bug in `cs_close` that corrupted the memory (no idea how that didn't cause issues earlier). Regarding your issue, it turns out the way I computed offsets in for the `cs_detail` members was wrong. This is now fixed and works fine with `CS_ARCH_X86`, as of 8f488ca.

The `cs_detail` members for the remaining architectures still need to be fixed (and the architectures added in Capstone 4.x need to be added to the wrapper as well). Other than that, regular decoding works fine.
